### ISSUE TITLE
The server can only handle one player

### ISSUE THREAD

**Issue by paisendevmc** [mmbednarek/minecpp#23]
The server can only handle one player. When I try to connect from the second client, I get an error and disconnect with an error from two clients.

![image](https://user-images.githubusercontent.com/64857329/217914238-65ed7cc5-1b97-4983-b1c1-76fd45c6b4e7.png)

![image](https://user-images.githubusercontent.com/64857329/217914300-0d267a4d-5508-428c-8044-de4ee3a7a344.png)

Log: https://pastebin.com/uqpgNmbK

**Comment by mmbednarek** [comment]
Yes, that issue is now fixed. Thank you for your submission.
