### ISSUE TITLE
ninja: error: unknown target 'minecpp_event'

### ISSUE THREAD

**Issue by 0pi03** [mmbednarek/minecpp#27]
After running 'make docker-run', I end up with an error.

Step 11/11 : RUN cmake --build . -j $(nproc) -t minecpp_game    -t minecpp_controller    -t minecpp_event    -t minecpp_engine_api    -t minecpp_utils    -t minecpp_game    -t minecpp_api_proto    -t minecpp_nbt    -t minecpp_chat    -t minecpp_format    -t minecpp_network    -t minecpp_repository    -t minecpp_command    -t minecpp_storage_api    -t minecpp_lexer    -t minecpp_crypto   -t yaml-cpp
 ---> Running in 627f2fe03c15
[0/2] Re-checking globbed directories...
ninja: error: unknown target 'minecpp_event', did you mean 'minecpp_front'?
![Screenshot_20230212_141527_com termux](https://user-images.githubusercontent.com/105676018/218307762-bb1890cf-95e2-4d05-b612-89b388a2e7d2.jpg)

**Comment by mmbednarek** [comment]
Thank you for your submission. I am sorry I've changed `minecpp_event` library to be header only and haven't noticed it broke docker build.
